# Mod metadata
version = 0.1.0
mod_id = reinforced_tools
mod_name = ReinforcedTools
group = dev.toliner.reinforcedtools
description = A Minecraft mod built with Balm for Fabric and NeoForge.
license = MPL-2.0
mod_author = toliner
homepage =
sources =
issues =
discord =
credits =

# Loader selection
include_fabric = true
include_neoforge = true

# Optional NeoForge snapshot repository
neoforge_snapshot_url =

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
