pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = uri('https://maven.fabricmc.net')
                }
            }
            filter {
                includeGroupAndSubgroups('net.fabricmc')
                includeGroup('fabric-loom')
            }
        }
    }
}

rootProject.name = 'ReinforcedTools'

includeBuild('build-logic')
include('common')
if (providers.gradleProperty('include_fabric').getOrElse('true') == 'true') {
    include('fabric')
}
if (providers.gradleProperty('include_neoforge').getOrElse('true') == 'true') {
    include('neoforge')
}
